try:
	print("test")
except Exception as err:
	print(err)
